### ISSUE TITLE
Error opening model2009-publicmm1-bfm.h5

### ISSUE THREAD

**Issue by inspirit** [unibas-gravis/scalismo-ui#11]
Hello,

I've cloned latest version and did ```sbt run```
then tried to open official ```model2009-publicmm1-bfm.h5``` model file which resulted in following error:
"Unable to load file: Expected H5ScalarDS when reading attribute"

**Comment by marcelluethi** [comment]
@inspirit Thanks for reporting this. Since the Basel Face model does not only store shape, but also texture, its h5 file has a more complicated format than a standard shape model. This more complicated case was indeed not yet supported by Scalismo-ui. It should be fixed with PR #12 . Once it is merged you can just update your master branch and everything should work as expected.

**Comment by inspirit** [comment]
I see, thanks for the info.
Looking forward

**Comment by marcelluethi** [comment]
The version that is in the current master branch should now resolve the issue. 
We have also just published a release candidate [0.12.0-RC1](https://github.com/unibas-gravis/scalismo-ui/releases/tag/v0.12.0-RC1) which contains this fix and some other improvements.
