### ISSUE TITLE
ScalarMeshField 3D-visualisation

### ISSUE THREAD

**Issue by madsendennis** [unibas-gravis/scalismo-ui#39]
An issue with visualisation of scalar mesh fields in Scalismo-UI. 
Setting both scalar range sliders to their minimum should give a complete red mesh. This works in the 2D slices, but in 3D, the vertices with the minimum value in the scalar range will still be coloured blue.

![scalarFieldMin](https://user-images.githubusercontent.com/12571611/68753028-98b73200-0604-11ea-83aa-68abaaf9e691.png)

![scalarFieldMax](https://user-images.githubusercontent.com/12571611/68753037-9b198c00-0604-11ea-8493-ce06a1b4405f.png)

**Comment by clangguth** [comment]
I agree that this is a bug, in the sense that it is inconsistent visualization.

However, the problem is that by defining the values this way (min=max), the range of colors is actually nonexistent (technically: any "step" between min and max, however small, becomes a division by zero). 

Or to put it another way: all values (min=value=max) must be "red" AND "blue" at the same time, which is impossible. The actual visualization is provided by vtk, and obviously it - thankfully - decides to at least not crash, but it does seem to handle things slightly differently in 2D vs 3D.

That said, I currently don't know a good way to fix this.

**Comment by madsendennis** [comment]
Hi @clangguth , thanks for the input. It seems that this is now fixed with the color scheme picker in #42  . I, therefore, close the issue.
