### ISSUE TITLE
Saving Images from UI changes type

### ISSUE THREAD

**Issue by kahrpatrick** [unibas-gravis/scalismo-ui#47]
Observation: A DiscreteScalarImage[_3D, Short] loaded into the UI (either trough the UI, or added with 'ui.show') gets transformed into a DiscreteScalarImage[_3D, Float] when saving it from the UI.

Expected behaviour: Scalar type should not change when saving the image.

**Comment by marcelluethi** [comment]
Thanks for reporting. This is, however, not really a bug but a design decision. It turned out to be unnecessarily complicated to maintain the scalar type as a type parameter in the ui. Therefore we decided to convert the image to float at the beginning and then only work with float images. For visualization purposes, it does not really make a difference. For saving it is annoying, but we don't think that this is a very common use case. 

If you think that we should change it, you can reopen an issue as a proposal for enhancement.
