### ISSUE TITLE
Change landmark size

### ISSUE THREAD

**Issue by eosulliv** [unibas-gravis/scalismo-ui#48]
The quickstart documentation shows how the colour of both meshes and landmarks in the Scalismo UI can be changed quite easily. Is there a similar functionality available for changing the size of landmarks? I found a previous reference to this issue on a google group, but no solution was available at the time.

Some of the meshes I am working with fit within a unit sphere - importing meshes landmarks results in beach ball sized landmark points that completely obscure the mesh and make it impossible to see if these landmarks actually represent the points that they should. Can the size of the landmarks be decreased in code? It does not seem to be possible fro the Scalismo UI.

**Comment by clangguth** [comment]
Hi,

this is something that is not terribly easy with the current version of scalismo, or scalismo-ui, but it's still doable.

Some background: the reason for this is because where scalismo comes from, a landmark isn't just a simple point, but a point with an additional uncertainty (see [Landmark.scala](https://github.com/unibas-gravis/scalismo/blob/34ee51f8077d8b475400993cc1d9450b178718fd/src/main/scala/scalismo/geometry/Landmark.scala#L21)).

A landmark's shape in fact represents that - it's not simply a point drawn with a sphere around it, but really an ellipsoid where the ellipsoid's shape shows the uncertainty, as reflected in the [landmark rendering code](https://github.com/unibas-gravis/scalismo-ui/blob/020aae765941c77042a818f0d8a329df7132a13c/src/main/scala/scalismo/ui/rendering/actor/LandmarkActor.scala#L66).

Now, not all landmarks come with an uncertainty set (actually, my guess is that for most people, it will not be set), but the UI still requires one in order to even render the landmark. Hence, there's a default value defined [here](https://github.com/unibas-gravis/scalismo-ui/blob/master/src/main/scala/scalismo/ui/model/properties/Uncertainty.scala#L37), and this is what you're seeing. It's a default uncertainty with the axes set to the standard X, Y, and Z axes, and a value of 1.0 in each direction.

So... what to do?

That depends on how you're using the software. If you don't really care about the actual underlying concept of uncertainties, and you're fine with having all landmarks shown with a fixed radius (e.g. 0.2), the easiest solution is something like the following:


```scala
  def main(args: Array[String]): Unit = {
    scalismo.ui.model.properties.Uncertainty.DefaultUncertainty = scalismo.ui.model.properties.Uncertainty.DefaultUncertainty.copy(sigmas = List(.2,.2,.2))
    val ui = ScalismoUI()
    /* other code */
  }
```

Another option, if you're creating landmarks programmatically, is to explicitly specify the uncertainty at creation time of the landmark. Here would be a [starting point](https://github.com/unibas-gravis/scalismo-ui/blob/020aae765941c77042a818f0d8a329df7132a13c/src/main/scala/scalismo/ui/model/properties/Uncertainty.scala#L52).

For a more user-friendly solution, I agree that it would be nice to have a UI component, and/or the possibility to programmatically change it similarly to [other properties](https://github.com/unibas-gravis/scalismo-ui/blob/master/src/main/scala/scalismo/ui/api/Views.scala#L429).

However, that would be a major problem, because all of the (view) properties are only meant to be purely cosmetic (like, which color to show, what line width to use etc.), and do not affect the underlying (immutable) model data. However, the uncertainty of a landmark is part of the underlying model, not of the view.

Ideas from other scalismo folks are more than welcome :)

**Comment by eosulliv** [comment]
Hi,
Thank you for your reply and for the background on why adding a size parameter to the landmarks is not an easy thing to do. For visualisation purposes, the workaround you propose is works perfectly. I'll just have to be careful to remember that all the uncertainties have been  hanged in this way when doing this.
